name: 4 - Workflow CD Application dans AKS

on:
  workflow_dispatch:

env: # variables
  RG_NAME: "RG-AKSCluster-ABL"
  CLUSTER_NAME: "AKS-000" 
  REGISTRY_NAME: "acrabl2022"
  REGISTRY_USERNAME: "acrabl2022"
  APP_NAME: "coolapi"
  IMAGE_VERSION: "1.0.0"

jobs:

  Deploy-App-Aks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ env.RG_NAME }} --name ${{ env.CLUSTER_NAME }}
  
      - name: Deploiement application dans AKS
        run: |      
          cd Kubernetes/Manifests/coolapi          
          kubectl apply -f 1_namespace.yml
          kubectl create secret docker-registry acr-secret -n coolapi --docker-server=${{ env.REGISTRY_NAME}}.azurecr.io --docker-username=${{ env.REGISTRY_USERNAME}} --docker-password=${{ secrets.REGISTRY_PASSWORD }}
          kubectl apply -f 2_deployment.yml
          kubectl apply -f 3_service.yml


